# docker-compose.yml

services:
  voice_bot:
    container_name: whisper_voice_bot
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build:
      context: .
      dockerfile: Dockerfile
    image: the80hz/utgb:latest
    env_file:
      - .env
    restart: unless-stopped