version: '3.8'

services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./voice_messages:/app/voice_messages
      - ./video_notes:/app/video_notes